<a href="https://colab.research.google.com/github/Rutujakb592/Python_Libraries/blob/main/Panadas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
# import pandas
import pandas as pd

In [3]:
pd.__version__ # check installed pandas version

'2.2.2'

What is Dataframe?
It's a structured data constructed with rows and columns, similar to a SQL tables or Excel tables

**1. Create Dataframe**

In [5]:
# using a List
df = pd.DataFrame([11,22,33], columns=['Col_Name'])
print(df)

   Col_Name
0        11
1        22
2        33

In [6]:
print(type(df)) # check data type

<class 'pandas.core.frame.DataFrame'>

In [7]:
# using Dictionary of Lists
data = {
    'Name': ['Madhav', 'Vishakha', 'Lalita', 'Rishabh'],
    'Age': [16,17,18,19],
    'Salary': [90000, 70000, 50000, 30000]
}

In [8]:
df = pd.DataFrame(data)
print(df)

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [9]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

2 Basic Dataframe Understanding

In [10]:
df.head(2) # top rows

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000

In [11]:
df.tail(2) # last rows

      Name  Age  Salary
2   Lalita   18   50000
3  Rishabh   19   30000

In [12]:
df.shape # returns a tuple containing the shape of the DataFrame - rows & columns

(4, 3)

In [13]:
df.columns # list of column names in a dataframe

Index(['Name', 'Age', 'Salary'], dtype='object')

In [14]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace=True) # rename column name/s

In [15]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [16]:
df.info()  # info method prints information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes